# crea una imagen de nombre    : dockerizingdjango_web
# crea un contenedor de nombre : dockerizingdjango_web_1
# para ejecutar un comando en el servicio web
version: '2'
services:
    web:
      restart: always
      build: . # refecia al DockerFile
      ports:
        - "8079:8000" # puerto HOST:CONTAINER
      volumes:
        - .:/code
      links:
        - db
    db:
      restart: always
      image: postgres
      ports:
        - "5432:5432"
